### ISSUE TITLE
http://xbmcfilm.com/ not working

### ISSUE THREAD

**Issue by piotrekcrash** [mrknow/xbmcfilm.com#2]
Are You close this project? Page http://xbmcfilm.com/ is unavailable long time.

**Comment by mrknow** [comment]
I lost my patience to delete pirated links. I rebuild page and run a personalized list of movies

**Comment by piotrekcrash** [comment]
Thanks for answer. This addon is very useful for me. Let's consider also links from: http://filmy.to
Thanks for Your work.
